typography_spectrum: 0.74886
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.39204393420368433
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.741
analytics:
  google: null
  facebook: null
  twitter: null
name: heartastrology
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Heartastrology
description: 'An exploration of time, space, and interdependence'
purpose: []
