name: heartastrology
favicon: null
layout_spectrum: 0.14741984708234668
typography_spectrum: 0.019019606756046414
title: Heartastrology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.39204393420368433
  rhythmicContrast: 0.5
purpose: []
